name: Java CI

on:
    workflow_dispatch:
    push:
        branches:
            - '**'
        tags-ignore:
            - '*.*'

jobs:
    build:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 11
                uses: actions/setup-java@v4
                with:
                    java-version: 11
                    distribution: 'temurin'
            -   name: Build with Gradle
                run: ./gradlew build publishToSonatype closeAndReleaseSonatypeStagingRepository
                env:
                    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
                    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
                    ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatypeUsername }}
                    ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatypePassword }}
